{
	"version": 1740303226,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/exosphere-sheet0.png",
		"images/thermosphere-sheet0.png",
		"images/mesosphere-sheet0.png",
		"images/stratosphere-sheet0.png",
		"images/troposphere-sheet0.png",
		"images/maincity-sheet0.png",
		"images/clouds-sheet0.png",
		"images/plane-sheet0.png",
		"images/rock1-sheet0.png",
		"images/rock2-sheet0.png",
		"images/satellite1-sheet0.png",
		"images/satellite2-sheet0.png",
		"images/star-sheet0.png",
		"images/rockket-sheet0.png",
		"images/deadzone.png",
		"images/startbg-sheet0.png",
		"images/book-sheet0.png",
		"images/book-sheet1.png",
		"images/storms-sheet0.png",
		"images/bird-sheet0.png",
		"images/bomb-sheet0.png",
		"images/laser-sheet0.png",
		"images/planee-sheet0.png",
		"images/cars-sheet0.png",
		"images/player-sheet0.png",
		"media/90s-game-ui-15-185108.ogg",
		"media/achievement-video-game-type-1-230515.ogg",
		"media/change level.ogg",
		"media/coin-recieved-230517.ogg",
		"media/game-level-complete-143022.ogg",
		"media/grab item.ogg",
		"media/grab more bonus.ogg",
		"media/item bonus.ogg",
		"media/musicloop.ogg",
		"media/success-221935.ogg",
		"media/touch monster.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}